### ISSUE TITLE
Support using Golang Dep

### ISSUE THREAD

**Issue by darrenhaken** [terraform-providers/terraform-provider-aws#2864]
I've started to look at contributing to the AWS provider and it would be beneficial to add dependency management via [Golang's Dep](https://github.com/golang/dep).

If I added this to the project would a PR be accepted?

**Comment by bflad** [comment]
Hi @darrenhaken, I cannot speak for the other maintainers, but some questions of mine:

[dep homepage](https://github.com/golang/dep):
> dep is the official experiment, but not yet the official tool.
[dep roadmap](https://github.com/golang/dep/wiki/Roadmap):
> Please remember that finishing these issues does not guarantee dep will be accepted.

Is there a particular reason why we want to implement this before its official?

> it would be beneficial to add dependency management via Golang's Dep

Can you elaborate? We already use [govendor](https://github.com/kardianos/govendor) to manage our dependencies in this project as well as the other Terraform providers currently. I think there would need to be a larger discussion to do this to the Terraform core project and the other providers as well since they are maintained similarly. Are there issues resolved in switching from `govendor`?

By all means, I'm not saying no, just curious about your thoughts on these and the thoughts of other maintainers. We have a large amount of backlog work relating to functionality/bugfixes already. 😄

**Comment by darrenhaken** [comment]
Hi Brian,

To add to the context of Dep, it’s part of the official Go repositories and whilst it’s still not “official” they do mention in the docs it’s ready for production use:

“dep is safe for production use. That means two things:

Any valid metadata file (Gopkg.toml and Gopkg.lock) will be readable and considered valid by any future version of dep.
The CLI UI is mostly stable. dep init and dep ensure are mostly set; dep status is likely to change a fair bit, and dep prune is going to be absorbed into dep ensure.”

I am actually new to Go and I’ve picked up my first issue to contribute to the Terraform codebase; I’ll fully admit that my questions may come from a lack of knowledge of idiomatic ways to manage dependencies.

I hadn’t heard of govendor so I’ll take a look but benefits I saw to Dep are:
- It creates a file describing versions of packages the application depends on
- Creates a lock file to pin versions, like package.lock in node if you’re familiar with that.

I understand you might be swamped right now so it might not be a priority yet, I wasn’t sure if anyone on the core team was aware of its existence.

Let me know if you want to discuss further.

Cheers,

Darren



________________________________

**Comment by darrenhaken** [comment]
Forgot to add I ran a single command to setup Dep on the AWS Terraform provider and it seemed to work; migration might be fairly low cost in the future.

**Comment by radeksimko** [comment]
Hi @darrenhaken 

> If I added this to the project would a PR be accepted?

Short answer: Not at this point in time.

Longer answer: We plan to use dep eventually, here's full explanation: https://github.com/terraform-providers/terraform-provider-aws/pull/2652#pullrequestreview-83214854

**Comment by darrenhaken** [comment]
@radeksimko thanks for the answer. I'll close this the issue, it sounds like it might be some time before the core TF repository is ready.
